trigger:
  branches:
    include:
      - prev  # merging into `prev`
  paths:
    exclude:
      - azure-pipelines-prev.yml
      
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --no-restore --configuration Release
  displayName: 'Build'

- script: dotnet test --no-build --configuration Release --logger trx
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/*.trx'

# STEP 1: dotnet publish to output deployable files
- script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish App'

# I dont really need this because I dont use the resulting artifact anywhere
# STEP 2: Publish artifacts 
#- task: PublishBuildArtifacts@1
#  inputs:
#    pathToPublish: '$(Build.ArtifactStagingDirectory)'
#    artifactName: 'drop'
#    publishLocation: 'Container'

# STEP 3: Deploy that artifact Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Connection2Azure'  
    appType: 'webApp'                     # I think thats the windows standard version
    appName: 'app-service-homelab'              
    package: '$(Build.ArtifactStagingDirectory)' 
